In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [5]:
# One Hot Representation
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr
    

[[2892, 6456, 1226, 8792],
 [2892, 6456, 1226, 1493],
 [2892, 8164, 1226, 1025],
 [9686, 8856, 3669, 9114, 6829],
 [9686, 8856, 3669, 9114, 7628],
 [8191, 2892, 2514, 1226, 8528],
 [7954, 9381, 3912, 9114]]

In [6]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length = 8
Embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(Embedded_docs)

[[   0    0    0    0 2892 6456 1226 8792]
 [   0    0    0    0 2892 6456 1226 1493]
 [   0    0    0    0 2892 8164 1226 1025]
 [   0    0    0 9686 8856 3669 9114 6829]
 [   0    0    0 9686 8856 3669 9114 7628]
 [   0    0    0 8191 2892 2514 1226 8528]
 [   0    0    0    0 7954 9381 3912 9114]]


In [8]:
# Feature representation
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.build(input_shape=(None, sent_length))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(Embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


array([[[ 0.02399084,  0.00791433, -0.04276835, -0.04708682,
          0.0432389 ,  0.04377637,  0.02430527,  0.03182024,
          0.00377178, -0.02502601],
        [ 0.02399084,  0.00791433, -0.04276835, -0.04708682,
          0.0432389 ,  0.04377637,  0.02430527,  0.03182024,
          0.00377178, -0.02502601],
        [ 0.02399084,  0.00791433, -0.04276835, -0.04708682,
          0.0432389 ,  0.04377637,  0.02430527,  0.03182024,
          0.00377178, -0.02502601],
        [ 0.02399084,  0.00791433, -0.04276835, -0.04708682,
          0.0432389 ,  0.04377637,  0.02430527,  0.03182024,
          0.00377178, -0.02502601],
        [ 0.00576733, -0.00651984,  0.03298165, -0.01302218,
          0.04922261, -0.01954621,  0.00641895, -0.00893723,
          0.03762174, -0.03858476],
        [-0.04268186, -0.00920925,  0.0302623 , -0.01296609,
          0.00745473,  0.00207385, -0.00825102,  0.01688569,
          0.03563296,  0.02064991],
        [ 0.01314641, -0.01040566,  0.00398107,  0.0

In [15]:
Embedded_docs[0]

array([   0,    0,    0,    0, 2892, 6456, 1226, 8792], dtype=int32)